<!DOCTYPE html>
<html>
    <head>
        <style>
            <?php require 'assets/main.css' ?>
        </style>
        <style>
            <?php require 'assets/debug.css' ?>
        </style>
        <script >
            var Queue = [];
        </script>
    </head>
    <body>
        <main>
            <section>
                <h1>
                    Ops,
                </h1>
                <p>
                    <?= $message ?>
                </p>
            </section>
        </main>
    </body>
</html>
